using UnityEngine;

namespace ProjectLEA.Manuel
{
    /// <summary>
    /// Drives the bean's animator from its own observed movement.
    ///
    /// The same component serves three very different owners, so it never reads input:
    /// the local player's body is the only one with a <see cref="PlayerController"/> and
    /// the only one that should crouch; the network-driven proxy and the stand-in dummy
    /// get their position written by somebody else and simply need the walk clip to match
    /// how fast they are actually moving. Measuring the horizontal delta per frame works
    /// for all three and needs no wiring.
    ///
    /// The animator itself is generated by ContentSetup from the clips baked into the
    /// bean FBX: two 1D blend trees (standing and crouching) on a "Speed" parameter,
    /// switched by a "Crouch" bool.
    /// </summary>
    [DisallowMultipleComponent]
    [RequireComponent(typeof(Animator))]
    public class BeanAnimation : MonoBehaviour
    {
        private const string SpeedParam = "Speed";
        private const string CrouchParam = "Crouch";

        [Tooltip("Seconds it takes for the walk weight to catch up with a speed change. " +
                 "Low enough to react to a direction change, high enough that the stride " +
                 "does not stutter on a frame hitch.")]
        [SerializeField] private float speedSmoothing = 0.12f;

        [Tooltip("Horizontal speed in m/s at which the walk clip is at full weight. The " +
                 "classes move between roughly 3 and 8 m/s, so this keeps a normal walk " +
                 "from looking like a sprint.")]
        [SerializeField] private float fullWalkSpeed = 6f;

        private Animator _animator;
        private PlayerController _owner;
        private Vector3 _lastPosition;
        private float _smoothedSpeed;
        private bool _parametersPresent;

        private void Awake()
        {
            _animator = GetComponent<Animator>();
            // Crouch is a local input state, so only the local player's bean can do it.
            // A null owner is not a failure: the proxy and the dummy are supposed to be
            // null here, and they stay in the standing blend tree.
            _owner = GetComponentInParent<PlayerController>();
            _lastPosition = transform.position;
        }

        private void Start()
        {
            // An animator built for a different rig, or one still missing its parameters,
            // would log a warning every frame from here on. Check once and stay quiet.
            if (_animator == null || _animator.runtimeAnimatorController == null) return;
            foreach (var parameter in _animator.parameters)
            {
                if (parameter.name == SpeedParam || parameter.name == CrouchParam)
                {
                    _parametersPresent = true;
                    break;
                }
            }
        }

        private void Update()
        {
            if (_animator == null || !_parametersPresent) return;

            Vector3 moved = transform.position - _lastPosition;
            _lastPosition = transform.position;
            moved.y = 0f;

            float raw = Time.unscaledDeltaTime > 0f
                ? moved.magnitude / Time.unscaledDeltaTime
                : 0f;

            // A respawn teleports the body; without a clamp that one frame reads as a sprint
            // and the walk blend snaps to full for a beat.
            raw = Mathf.Min(raw, fullWalkSpeed * 3f);

            // unscaledDeltaTime, not deltaTime: the match UIs freeze time, and the blend
            // would otherwise snap to idle every time a menu opened.
            float t = Time.unscaledDeltaTime > 0f
                ? Mathf.Clamp01(Time.unscaledDeltaTime / Mathf.Max(0.01f, speedSmoothing))
                : 1f;
            _smoothedSpeed = Mathf.Lerp(_smoothedSpeed, raw, t);

            _animator.SetFloat(SpeedParam, _smoothedSpeed / fullWalkSpeed);
            _animator.SetBool(CrouchParam, _owner != null && _owner.IsCrouching);
        }
    }
}
